Changed some names in the scripts that Anton missed in the previous commit. The scripts build-gcc* and makeExtraThirdPartyFunctions have been updated and tested sucessfully in old CentOSes Workstations i383 3.3, 3.9, 4.0 and 4.8 (all virtual machines).

diff --git a/common/files/build-gcc45 b/common/files/build-gcc45
--- a/common/files/build-gcc45
+++ b/common/files/build-gcc45
@@ -60,9 +60,11 @@ GMPVERSION="gmp-5.0.1"
 MPFRVERSION="mpfr-2.4.2"
 MPCVERSION="mpc-0.8.2"
 BINUTILSVERSION="binutils-2.20.1"
+MAKEVERSION="make-3.82"
 
 BUILDS_CLEANUP_AT_END=1 #0 - don't remove the build directories at the end; 1 - remove the build directories at the end
 HOMES_CLEANUP_AT_END=1 #0 - don't remove the home directories of unpacked files at the end; 1 - remove the home directories of unpacked files at the end
+BUILD_MAKE=1 #0 - don't build an up-to-date make; 1 - build an up-to-date make, which is useful for older systems
 
 #LOG FOLDER
 LOG_FOLDER="$WM_THIRD_PARTY_DIR/../buildLogs"
@@ -97,6 +99,7 @@ GMP_HOME="$WM_THIRD_PARTY_DIR/$GMPVERSION"
 MPFR_HOME="$WM_THIRD_PARTY_DIR/$MPFRVERSION"
 MPC_HOME="$WM_THIRD_PARTY_DIR/$MPCVERSION"
 BINUTILS_HOME="$WM_THIRD_PARTY_DIR/$BINUTILSVERSION"
+MAKE_HOME="$WM_THIRD_PARTY_DIR/$MAKEVERSION"
 REPORTMISSINGFILES="${DownloadRepository}/downloadReportProblems.txt"
 
 PREFIX="${WM_THIRD_PARTY_DIR}/platforms/$WM_ARCH$WM_COMPILER_ARCH/$GCCVERSION"
@@ -135,6 +138,7 @@ LOG_FOLDER=`( cd "$LOG_FOLDER" && pwd )`
 
 GCC_BDIR="$buildBASE/$GCCVERSION"
 BINUTILS_BDIR="$buildBASE/$BINUTILSVERSION"
+MAKE_BDIR="$buildBASE/$MAKEVERSION"
 
 #
 # Set the number of cores to build on
@@ -151,17 +155,17 @@ GMP_TARFILE="${GMPVERSION}.tar.bz2"
 MPFR_TARFILE="${MPFRVERSION}.tar.bz2"
 MPC_TARFILE="${MPCVERSION}.tar.gz"
 BINUTILS_TARFILE="${BINUTILSVERSION}.tar.bz2"
+MAKE_TARFILE="${MAKEVERSION}.tar.bz2"
 
 GNU_URL="ftp://ftp.mirrorservice.org/sites/sourceware.org/pub/gcc/releases/${GCCVERSION}/${GCC_TARFILE}"
 GMP_URL="ftp://ftp.gnu.org/gnu/gmp/${GMP_TARFILE}"
 MPFR_URL="ftp://ftp.gnu.org/gnu/mpfr/${MPFR_TARFILE}"
 MPC_URL="http://www.multiprecision.org/mpc/download/${MPC_TARFILE}"
 BINUTILS_URL="ftp://ftp.mirrorservice.org/sites/sourceware.org/pub/binutils/releases/${BINUTILS_TARFILE}"
+MAKE_URL="ftp://ftp.gnu.org/gnu/make/${MAKE_TARFILE}"
 
 # Make sure these are initialized as we want them
 
-GCC_CORE=""
-BINUTILS=""
 GCC_LANGS="c,c++"
 
 
@@ -202,6 +206,9 @@ download_files()
   downloadFile $MPFR_TARFILE $MPFR_URL
   downloadFile $MPC_TARFILE $MPC_URL
   downloadFile $BINUTILS_TARFILE $BINUTILS_URL
+  if [ "x$BUILD_MAKE" = "x1" ]; then
+    downloadFile $MAKE_TARFILE $MAKE_URL
+  fi
 
   if [ -e "${REPORTMISSINGFILES}" ]; then rm "${REPORTMISSINGFILES}"; fi
   checkAndReport $GCC_TARFILE $GNU_URL
@@ -209,6 +216,9 @@ download_files()
   checkAndReport $MPFR_TARFILE $MPFR_URL
   checkAndReport $MPC_TARFILE $MPC_URL
   checkAndReport $BINUTILS_TARFILE $BINUTILS_URL
+  if [ "x$BUILD_MAKE" = "x1" ]; then
+    checkAndReport $MAKE_TARFILE $MAKE_URL
+  fi
   if [ -e "${REPORTMISSINGFILES}" ]; then
     echo "It seems that some files were not downloaded with success. Please see the file:"
     echo "   ${REPORTMISSINGFILES}"
@@ -254,6 +264,9 @@ unpack_files()
   if [ ! -d $MPFRVERSION ]; then unpackFile $MPFR_TARFILE; fi
   if [ ! -d $MPCVERSION ]; then unpackFile $MPC_TARFILE; fi
   if [ ! -d $BINUTILSVERSION ]; then unpackFile $BINUTILS_TARFILE; fi
+  if [ "x$BUILD_MAKE" = "x1" ]; then
+    if [ ! -d $MAKEVERSION ]; then unpackFile $MAKE_TARFILE; fi
+  fi
 
   #fix links for GMP and MPFR
   do_links_GM
@@ -271,6 +284,53 @@ do_links_GM()
   fi
   if [ ! -d "$GCC_HOME/mpc" ]; then
     ln -s $MPC_HOME $GCC_HOME/mpc
+  fi
+}
+
+
+configure_make()
+{
+  if [ -d "$MAKE_BDIR" ]; then rm -rf "$MAKE_BDIR"; fi
+  mkdir -p "$MAKE_BDIR"
+  cd "$MAKE_BDIR"
+  echo "Configuring make"
+  "$MAKE_HOME/configure" --prefix=${PREFIX} \
+      --disable-multilib \
+      --with-host-libstdcxx='-lstdc++' --with-gcc \
+      --with-gnu-as --with-gnu-ld --enable-shared --disable-rpath \
+      --disable-werror \
+      > ${LOG_FOLDER}/make-${WM_COMPILER}_configure.log  2>&1
+
+      ##--with-sysroot=${PREFIX}
+  if test $? -ne 0; then
+    echo "make of make failed - log available: ${LOG_FOLDER}/make-${WM_COMPILER}_configure.log"
+    exit 1
+  fi
+}
+
+
+build_make()
+{
+  cd "$MAKE_BDIR"
+  echo "Building make"
+  # -fno-exceptions
+  make -j $WM_NCOMPPROCS CFLAGS="-O2" LDFLAGS="-s" > \
+    ${LOG_FOLDER}/make-${WM_COMPILER}_make.log 2>&1
+  if test $? -ne 0; then
+    echo "make of make failed - log available: ${LOG_FOLDER}/make-${WM_COMPILER}_make.log"
+    exit 1
+  fi
+}
+
+
+install_make()
+{
+  cd "$MAKE_BDIR"
+  echo "Installing make"
+  make install > ${LOG_FOLDER}/make-${WM_COMPILER}_make-install.log 2>&1
+  if test $? -ne 0; then
+    echo "install of make failed - log available: ${LOG_FOLDER}/make-${WM_COMPILER}_make-install.log"
+    exit 1
   fi
 }
 
@@ -293,6 +353,9 @@ configure_binutils()
   if test $? -ne 0; then
     echo "make of binutils failed - log available: ${LOG_FOLDER}/binutils-${WM_COMPILER}_configure.log"
     exit 1
+  else
+    #Source of fix: http://wiki.osdev.org/Talk:GCC_Cross-Compiler#Texinfo
+    echo "MAKEINFO = :" >> Makefile
   fi
 }
 
@@ -388,6 +451,12 @@ final_clean_up()
 download_files
 
 unpack_files
+
+if [ "x$BUILD_MAKE" = "x1" ]; then
+  configure_make
+  build_make
+  install_make
+fi
 
 configure_binutils
 build_binutils
