Some fixes have been made. More to come...

diff --git a/of16x/main_functions b/of16x/main_functions
--- a/of16x/main_functions
+++ b/of16x/main_functions
@@ -9,6 +9,14 @@
 #Code -----------------------------------------
 echo "Sourcing Main functions for OpenFOAM 1.6.x ..."
 
+#source system related script
+if [ "x$INST_SYSTEM" != "x" -a "x${SCRIPT_WORKFOLDER}" != "x" ]; then
+  . ${SCRIPT_WORKFOLDER}/of${OF_SHORT_VERSION}/${INST_SYSTEM}/main_functions
+else
+  echo "The variable INST_SYSTEM and/or SCRIPT_WORKFOLDER is/are empty and they are crucial to exist! Aborting execution."
+  exit 1
+fi
+
 #FUNCTIONS ------------------------------------------------------------------------------
 
 #Defining packages and servers to download from
